language: node_js
node_js:
  - 0.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g karma
  - cd ./webapp
  - ./scripts/web-server.js > /dev/null &
  - sleep 1 # give server time to start

script:
  - karma start config/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox

# Do not run these on the travis server at this time.
# The end to end tests require the service to be running, but travis can't
# start the service for us.  So we would have to have the default point to
# a dedicated dev service instance that is reach-able by travis.  However, we
# require /etc/hosts to have an entry at this point to reach our current dev
# server.  So these tests should be run only locally for now.
#  - karma start config/karma-e2e.conf.js --reporters=dots --browsers=Firefox
